const state={page:'home',player:JSON.parse(localStorage.getItem('fn_player_v2')||'null'),cosmetics:[],map:null,shop:null,stats:null,history:JSON.parse(localStorage.getItem('fn_stats_history')||'[]'),lastSync:null};
const routes={home:'Accueil',map:'Carte',quests:'Défis',items:'Skins & objets',shop:'Boutique',profile:'Profil',live:'Données live'};
const icons={home:'⌂',map:'⌖',quests:'✓',items:'◈',shop:'🛒',profile:'◉',live:'↗'};
function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
function nav(){var h='<aside class="sidebar"><div class="brand"><div class="brand-mark">FN</div><span>Companion</span></div><nav class="nav">';Object.keys(routes).forEach(function(k){h+='<button class="'+(state.page===k?'active':'')+'" onclick="go(\''+k+'\')"><span>'+icons[k]+'</span>'+routes[k]+'</button>'});h+='</nav><div class="notice" style="margin:28px 8px 0"><strong>Données réelles</strong><br>Skins, carte et boutique chargés depuis une API Fortnite. Les stats personnelles demandent une clé API côté serveur.</div></aside>';return h}
function mobileNav(){var h='<div class="mobile-nav">';Object.keys(routes).slice(0,5).forEach(function(k){h+='<button class="'+(state.page===k?'active':'')+'" onclick="go(\''+k+'\')">'+icons[k]+'<br>'+routes[k]+'</button>'});return h+'</div>'}
function layout(content){document.querySelector('#app').innerHTML='<div class="shell">'+nav()+'<main class="main"><div class="topbar"><div><div class="eyebrow">FN COMPANION</div><div class="page-title">'+routes[state.page]+'</div></div><div class="toolbar"><input id="globalSearch" class="search" placeholder="Rechercher…" oninput="filterUI(this.value)"><button class="btn" onclick="refreshPage()">↻ Actualiser</button></div></div>'+content+'</main>'+mobileNav()+'</div>'}
function toast(m){var t=document.querySelector('#toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;right:18px;bottom:18px;z-index:50;background:#1b2131;border:1px solid #3b4562;color:#fff;padding:12px 15px;border-radius:12px;box-shadow:0 16px 40px #0006';document.body.appendChild(t)}t.textContent=m;clearTimeout(window.__toast);window.__toast=setTimeout(function(){t.remove()},2200)}
async function api(type,params){var qs=new URLSearchParams(params||{});var url='/api/fortnite?type='+encodeURIComponent(type)+(qs.toString()?'&'+qs.toString():'');var r=await fetch(url);var d=await r.json();if(!r.ok)throw new Error(d.error||'API indisponible');state.lastSync=new Date().toISOString();return d.data||d}
function cosmeticCard(c){var img=c.images&&(c.images.featured||c.images.icon||c.images.smallIcon);return '<article class="card item-card"><div class="cosmetic-img">'+(img?'<img loading="lazy" src="'+esc(img)+'" alt="'+esc(c.name||'Cosmétique')+'">':'✨')+'</div><div class="item-body"><div class="eyebrow" style="font-size:9px">'+esc((c.rarity&&(c.rarity.displayValue||c.rarity.value))||'Fortnite')+'</div><strong>'+esc(c.name||'Sans nom')+'</strong><div class="sub">'+esc((c.type&&(c.type.displayValue||c.type.value))||'Cosmétique')+'</div><button class="btn" onclick="addFav(\''+esc(c.id||'')+'\')">☆ Favori</button></div></article>'}
function mini(c){var img=c.images&&(c.images.icon||c.images.smallIcon);return '<div class="row"><div class="item"><div class="mini-img">'+(img?'<img src="'+esc(img)+'" alt="">':'✨')+'</div><div><strong>'+esc(c.name||'Cosmétique')+'</strong><div class="sub">'+esc((c.type&&(c.type.displayValue||c.type.value))||'Objet')+'</div></div></div><span class="tag">'+esc((c.rarity&&(c.rarity.displayValue||c.rarity.value))||'Fortnite')+'</span></div>'}
async function loadCosmetics(){if(state.cosmetics.length)return;try{var d=await api('cosmetics');state.cosmetics=(d||[]).filter(function(c){return c&&c.name}).slice(0,500)}catch(e){toast('Impossible de charger les skins')}}
function home(){layout('<section class="hero"><div class="eyebrow">TABLEAU DE BORD</div><h1>FN Companion se met à jour.</h1><p>Carte actuelle, cosmétiques réels, boutique et profil amélioré. Les données sont séparées de l’interface pour faciliter les mises à jour.</p><button class="btn primary" onclick="go(\'map\')">Explorer la carte</button> <button class="btn" onclick="go(\'items\')">Voir les skins</button> <button class="btn" onclick="go(\'shop\')">Boutique</button></section><section class="grid g4"><div class="card metric"><div class="label">Skins chargés</div><div class="value">'+(state.cosmetics.length||'—')+'</div><div class="sub">Battle Royale</div></div><div class="card metric"><div class="label">POI</div><div class="value">'+(state.map&&state.map.pois?state.map.pois.length:'—')+'</div><div class="sub">Carte actuelle</div></div><div class="card metric"><div class="label">Favoris</div><div class="value">'+((state.player&&state.player.favorites)||[]).length+'</div><div class="sub">Sur cet appareil</div></div><div class="card metric"><div class="label">Synchro</div><div class="value" style="font-size:20px">'+(state.lastSync?new Date(state.lastSync).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}):'—')+'</div><div class="sub">API</div></div></section><div style="height:16px"></div><section class="grid g2"><div class="card"><div class="section-title">Cosmétiques récents</div><div id="homeCosmetics"><div class="sub">Chargement…</div></div></div><div class="card"><div class="section-title">Profil</div><div class="row"><div><strong>'+(state.player&&state.player.displayName?esc(state.player.displayName):'Mon profil')+'</strong><div class="sub">Pseudo, favoris, statistiques et préférences.</div></div><button class="btn primary" onclick="go(\'profile\')">Ouvrir</button></div></div></section>');loadCosmetics().then(function(){var b=document.querySelector('#homeCosmetics');if(b)b.innerHTML=state.cosmetics.slice(0,4).map(mini).join('')})}
async function items(){layout('<div class="toolbar"><button class="tab active" onclick="renderItems(\'all\',this)">Tous</button><button class="tab" onclick="renderItems(\'outfit\',this)">Tenues</button><button class="tab" onclick="renderItems(\'backpack\',this)">Dos</button><button class="tab" onclick="renderItems(\'pickaxe\',this)">Pioche</button><button class="tab" onclick="renderItems(\'emote\',this)">Emotes</button></div><div id="itemsGrid" class="grid g3"><div class="card"><div class="sub">Chargement…</div></div></div>');await loadCosmetics();renderItems('all')}
function renderItems(filter,b){if(b){document.querySelectorAll('.tabs .tab').forEach(function(x){x.classList.remove('active')});b.classList.add('active')}var box=document.querySelector('#itemsGrid');if(!box)return;var list=state.cosmetics.filter(function(c){var t=((c.type&&c.type.value)||'').toLowerCase();return filter==='all'||t.indexOf(filter)>=0}).slice(0,60);box.innerHTML=list.length?list.map(cosmeticCard).join(''):'<div class="card"><div class="sub">Aucun résultat.</div></div>'}
function addFav(id){var c=state.cosmetics.find(function(x){return x.id===id});if(!c)return;state.player=state.player||{displayName:'Joueur',favorites:[]};state.player.favorites=state.player.favorites||[];var i=state.player.favorites.findIndex(function(x){return x.id===id});if(i>=0){state.player.favorites.splice(i,1);toast('Retiré des favoris')}else{state.player.favorites.unshift({id:id,name:c.name,image:(c.images&&(c.images.icon||c.images.smallIcon))||''});toast('Ajouté aux favoris')}localStorage.setItem('fn_player_v2',JSON.stringify(state.player))}
async function mapPage(){layout('<div class="toolbar"><button class="tab active">Battle Royale</button><button class="tab">POI</button><button class="tab">Itinéraire</button><span id="mapStatus" class="sub">Chargement de la carte…</span></div><div id="realMap" class="map map-real"></div><div style="height:16px"></div><section class="grid g3"><div class="card metric"><div class="label">POI</div><div id="poiCount" class="value">—</div></div><div class="card metric"><div class="label">Source</div><div class="value" style="font-size:22px">Fortnite API</div></div><div class="card metric"><div class="label">Interaction</div><div class="value">Active</div></div></section>');try{var d=await api('map');state.map=d;var map=document.querySelector('#realMap');var img=d.images&&(d.images.blank||d.images.zoomed||d.images.pois||d.images.all);map.innerHTML=(img?'<img class="map-image" src="'+esc(img)+'" alt="Carte Fortnite actuelle">':'')+'<div class="zone"></div><div class="mapinfo">Carte actuelle · POI réels</div>';var world=135000;(d.pois||[]).slice(0,80).forEach(function(p){var x=Number(p.location&&p.location.x),y=Number(p.location&&p.location.y);if(!isFinite(x)||!isFinite(y))return;var left=(y+world)/(2*world)*100,top=(1-(x+world)/(2*world))*100;if(left<1||left>99||top<1||top>99)return;var b=document.createElement('button');b.className='poi';b.style.left=left+'%';b.style.top=top+'%';b.textContent=p.name||'POI';b.onclick=function(){toast((p.name||'POI')+' sélectionné')};map.appendChild(b)});document.querySelector('#poiCount').textContent=(d.pois||[]).length;document.querySelector('#mapStatus').textContent='Carte synchronisée'}catch(e){document.querySelector('#realMap').innerHTML='<div class="notice map-error">'+esc(e.message)+'</div>'}}
function quests(){var qs=[['Top 10 dans une partie',8,10,1200],['Infliger 5 000 dégâts',3470,5000,800],['Jouer 5 parties avec un ami',3,5,650],['Visiter 3 points d’intérêt',3,3,500]];layout('<section class="grid g2"><div class="card"><div class="section-title">Suivi des objectifs</div><div class="list">'+qs.map(function(q){var pct=Math.min(100,q[1]/q[2]*100);return '<div class="row challenge"><div><strong>'+q[0]+'</strong><div class="sub">'+q[1].toLocaleString('fr-FR')+' / '+q[2].toLocaleString('fr-FR')+' · '+q[3]+' XP</div><div class="progress"><i style="width:'+pct+'%"></i></div></div><span class="tag">'+(q[1]>=q[2]?'Terminé':'En cours')+'</span></div>'}).join('')+'</div></div><div class="card"><div class="section-title">Suivi Fortnite</div><p class="sub">La progression native des quêtes n’est pas exposée ici sans accès authentifié autorisé.</p></div></section>')}
async function shop(){layout('<section class="hero"><div class="eyebrow">BOUTIQUE</div><h2>Objets actuellement proposés</h2><p>Les offres sont demandées au moment de l’ouverture de la page.</p></section><div id="shopGrid" class="grid g3"><div class="card"><div class="sub">Chargement…</div></div></div>');try{var d=await api('shop');state.shop=d;var entries=[].concat(d.featured||[],d.daily||[],d.specialFeatured||[],d.specialDaily||[]).flatMap(function(x){return x.entries||[x]}).filter(Boolean).slice(0,36);document.querySelector('#shopGrid').innerHTML=entries.map(function(e){var i=e.items&&e.items[0]||e.item||e;var img=i.images&&(i.images.icon||i.images.smallIcon);return '<div class="card item-card"><div class="cosmetic-img">'+(img?'<img src="'+esc(img)+'" alt="">':'🛒')+'</div><div class="item-body"><strong>'+esc(i.name||'Objet')+'</strong><div class="sub">'+(e.finalPrice!=null?esc(e.finalPrice)+' V-Bucks':'Offre')+'</div></div></div>'}).join('')||'<div class="card"><div class="sub">Aucune offre disponible.</div></div>'}catch(e){document.querySelector('#shopGrid').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
function statValue(obj,keys){
  for(var i=0;i<keys.length;i++){
    var key=keys[i];
    if(obj&&Object.prototype.hasOwnProperty.call(obj,key)&&obj[key]!==null&&obj[key]!==undefined)return obj[key];
  }
  return null
}
function findDeep(obj,keys,depth){
  if(!obj||depth>5)return null;
  var direct=statValue(obj,keys); if(direct!==null)return direct;
  if(typeof obj!=='object')return null;
  var vals=Array.isArray(obj)?obj: Object.keys(obj).map(function(k){return obj[k]});
  for(var i=0;i<vals.length;i++){var hit=findDeep(vals[i],keys,depth+1);if(hit!==null)return hit}
  return null
}
function normalizeStats(d){
  var stats=d&&d.stats||{};
  var account=d&&d.account||{};
  var wins=findDeep(stats,['br_wins_total','wins','victories'],0);
  var kills=findDeep(stats,['br_kills_total','kills','eliminations'],0);
  var deaths=findDeep(stats,['br_deaths_total','deaths'],0);
  var matches=findDeep(stats,['br_matches_total','matches','matchesPlayed'],0);
  var kd=findDeep(stats,['br_kd','kd','kdratio','killDeathRatio'],0);
  var winRate=findDeep(stats,['br_winrate','winRate','win_rate'],0);
  var minutes=findDeep(stats,['br_minutes_played','minutesPlayed','minutes_played'],0);
  var ranked=d&&d.ranked||null;
  var progress=d&&d.progress||null;
  return {
    account:account,
    battlePass:d&&d.battlePass||{},
    image:d&&d.image||null,
    wins:wins,kills:kills,deaths:deaths,matches:matches,kd:kd,winRate:winRate,
    score:findDeep(stats,['score','br_score'],0),
    minutesPlayed:minutes,
    lastModified:findDeep(stats,['lastModified','last_modified','updatedAt'],0),
    rank:findDeep(ranked,['rank','displayRank','division','tier','currentRank'],0),
    rankPoints:findDeep(ranked,['points','rating','score','rankPoints','rp'],0),
    rankedRaw:ranked,progress:progress
  }
}
async function loadStats(){
  var name=(state.player&&state.player.displayName||'').trim();
  if(!name){toast('Entre ton pseudo Epic');return}
  try{
    var d=await api('stats',{name:name});
    state.stats=normalizeStats(d);
    if(state.stats.account&&state.stats.account.name) state.player.displayName=state.stats.account.name;
    var snap={date:new Date().toISOString(),wins:state.stats.wins||0,kills:state.stats.kills||0,matches:state.stats.matches||0,kd:state.stats.kd||0,winRate:state.stats.winRate||0,rank:state.stats.rank||null};
    state.history=[snap].concat(state.history.filter(function(x){return Math.abs(new Date(x.date)-new Date(snap.date))>30000}).slice(0,14));
    localStorage.setItem('fn_player_v2',JSON.stringify(state.player));
    localStorage.setItem('fn_stats_history',JSON.stringify(state.history));
    state.lastSync=new Date().toISOString();
    toast('Stats mises à jour');
    profile();
  }catch(e){state.stats=null;toast('Stats indisponibles : '+e.message)}
}
function statDisplay(v){return v===null||v===undefined||v===''?'—':(typeof v==='number'?v.toLocaleString('fr-FR'):esc(v))}
function historyRows(){
  if(!state.history.length)return '<div class="sub">L’historique se construit à chaque actualisation de tes stats.</div>';
  return state.history.slice(0,10).map(function(h){
    return '<div class="row"><div><strong>'+new Date(h.date).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+'</strong><div class="sub">'+statDisplay(h.matches)+' parties · '+statDisplay(h.wins)+' victoires</div></div><div class="tag">K/D '+statDisplay(h.kd)+'</div></div>';
  }).join('');
}
async function profile(){
  var p=state.player||{favorites:[]};
  var s=state.stats;
  layout('<section class="card profile"><div class="avatar">'+(p.favorites&&p.favorites[0]&&p.favorites[0].image?'<img src="'+esc(p.favorites[0].image)+'" alt="">':'🎮')+'</div><div><div class="eyebrow">PROFIL FORTNITE</div><h2>'+((p.displayName&&esc(p.displayName))||'Mon profil')+'</h2><div class="toolbar"><input id="playerInput" class="search" placeholder="Pseudo Epic" value="'+esc(p.displayName||'')+'"><button class="btn primary" onclick="savePlayer()">Enregistrer</button><button class="btn" onclick="loadStats()">↻ Charger les stats</button></div><div class="sub" style="margin-top:9px">Les statistiques sont récupérées côté serveur avec ta clé API.</div></div></section><div style="height:16px"></div><section class="grid g4"><div class="card metric"><div class="label">Victoires</div><div class="value">'+(s?statDisplay(s.wins):'—')+'</div><div class="sub">Lifetime</div></div><div class="card metric"><div class="label">K/D</div><div class="value">'+(s?statDisplay(s.kd):'—')+'</div><div class="sub">'+(s?'Calcul API':'À charger')+'</div></div><div class="card metric"><div class="label">Parties</div><div class="value">'+(s?statDisplay(s.matches):'—')+'</div><div class="sub">Lifetime</div></div><div class="card metric"><div class="label">Rang</div><div class="value" style="font-size:21px">'+(s?statDisplay(s.rank):'—')+'</div><div class="sub">'+(s&&s.rank?'Source API':'Non exposé par la source')+'</div></div></section><div style="height:16px"></div><section class="grid g2"><div class="card"><div class="section-title">Battle Royale</div><div class="list"><div class="row"><span>Éliminations</span><strong>'+ (s?statDisplay(s.kills):'—') +'</strong></div><div class="row"><span>Morts</span><strong>'+ (s?statDisplay(s.deaths):'—') +'</strong></div><div class="row"><span>Taux de victoire</span><strong>'+ (s&&s.winRate!==null?statDisplay(s.winRate)+' %':'—') +'</strong></div><div class="row"><span>Minutes jouées</span><strong>'+ (s?statDisplay(s.minutesPlayed):'—') +'</strong></div><div class="row"><span>Battle Pass</span><strong>'+ (s&&s.battlePass&&s.battlePass.level!=null?statDisplay(s.battlePass.level):'—') +'</strong></div></div></div><div class="card"><div class="section-title">Historique des actualisations</div><div class="list">'+historyRows()+'</div></div></section>');
  if(p.favorites&&p.favorites.length){document.querySelector('#app').insertAdjacentHTML('beforeend','<div class="main profile-favorites" style="margin-left:245px;padding:0 25px 30px"><div class="card"><div class="section-title">Mes favoris</div><div class="grid g3">'+p.favorites.slice(0,9).map(function(f){return '<div class="row item"><div class="mini-img">'+(f.image?'<img src="'+esc(f.image)+'" alt="">':'✨')+'</div><strong>'+esc(f.name)+'</strong></div>'}).join('')+'</div></div></div>')}
}

function live(){layout('<div class="notice"><strong>Sources</strong><br>Cosmétiques, carte et boutique : proxy Vercel vers Fortnite-API.com. Les métriques agrégées d’îles peuvent aussi provenir de l’API de données Fortnite d’Epic.</div><div style="height:16px"></div><section class="grid g2"><div class="card"><div class="section-title">État</div><div class="list"><div class="row"><span>Cosmétiques</span><span class="tag">Live</span></div><div class="row"><span>Carte / POI</span><span class="tag">Live</span></div><div class="row"><span>Boutique</span><span class="tag">Live</span></div><div class="row"><span>Stats personnelles</span><span class="tag">Optionnelles</span></div></div></div><div class="card"><div class="section-title">Sécurité</div><p class="sub">Aucun mot de passe Epic n’est demandé. La clé API éventuelle est uniquement côté serveur.</p></div></section>')}
function savePlayer(){var v=(document.querySelector('#playerInput').value||'').trim();state.player=state.player||{favorites:[]};state.player.displayName=v;localStorage.setItem('fn_player_v2',JSON.stringify(state.player));toast('Profil enregistré');loadStats()}
function filterUI(v){var q=v.toLowerCase();document.querySelectorAll('.row,.item-card,.poi').forEach(function(el){el.style.display=el.innerText.toLowerCase().includes(q)?'':'none'})}
async function refreshPage(){if(state.page==='items')await items();else if(state.page==='map')await mapPage();else if(state.page==='shop')await shop();else if(state.page==='home')home();else toast('Page actualisée')}
function go(p){state.page=p;render();window.scrollTo(0,0)}
function render(){({home:home,map:mapPage,quests:quests,items:items,shop:shop,profile:profile,live:live}[state.page]||home)()}
render();